#!/bin/sh
#
# chkconfig: 345 90 90
# description: Starts Qubes GUI agent
#
# Source function library.
. /etc/rc.d/init.d/functions

start()
{
	echo -n $"Starting Qubes GUI agent:"
	rm -f /tmp/qubes-session-env /tmp/qubes-session-waiter
	DISPLAY=:0 /usr/bin/qubes_gui 2> /var/log/qubes/gui_agent.log &
	export DISPLAY=:0
	success
	echo ""
	return 0
}

stop()
{
	echo -n "Stopping Qubes GUI agent:"
	killall qubes_gui && success || failure
	echo ""
	return 0
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  *)
	echo $"Usage: $0 {start|stop}"
	exit 3
	;;
esac

exit $RETVAL
