#
# The Qubes OS Project, http://www.qubes-os.org
#
# Copyright (C) 2010  Rafal Wojtczuk  <rafal@invisiblethingslab.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
#

CC=gcc
CFLAGS+=-g -Wall -I../include
all: qubes_gui.stdin
qubes_gui.stdin: vmside.o xserver_fd.o ../gui-common/txrx-stdin.o ../common/list.o ../gui-common/error.o
	$(CC) $(LDFLAGS) -g -o qubes_gui.stdin vmside.o xserver_fd.o ../gui-common/txrx-stdin.o ../common/list.o ../gui-common/error.o \
		-lX11 -lXdamage -lXcomposite -Wall
clean:
	rm -f qubes_gui.stdin *.o *~
