#!/bin/bash
#
# The Qubes OS Project, http://www.qubes-os.org
#
# Copyright (C) 2011  Tomasz Sterna <tomek@xiaoka.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
#

# Switch user to 'user'
[[ "$USER" != "user" ]] && exec su user -c $0

# Get VM type from XenStore
VMTYPE=`/usr/bin/xenstore-read qubes_vm_type`

if [[ -n "$VMTYPE" ]] && [[ "$VMTYPE" != "DisposableVM" ]]; then
# Process XDG Autostart files
shopt -s nullglob
for D in /etc/xdg/autostart/*.desktop; do
	# Skip Terminal, Hidden, NotShowIn=QUBES and ! OnlyShowIn=QUBES
	MATCH="\(QUBES\|$VMTYPE\)"
	[[ -n `sed -n "/^Terminal.*[tT1]/p;/^Hidden.*[tT1]/p;/^NotShowIn.*=.*$MATCH/p;/^OnlyShowIn/{s/.*$MATCH.*//;p}" $D` ]] && continue
	# Extract Exec= line
	EXEC=`sed -n '/^Exec[ \t=]/s/^[^=]\+=[ \t]*//p' $D`
	[[ -z "$EXEC" ]] && continue
	$EXEC &
done
fi # VMTYPE

# Wait some time to pick up zombie children
sleep 1m

# Now hang myself so Xorg may live :'(
# ____
# |/ |
# |  O
# | /|\
# | / \
# |
kill -STOP $$
