#!/bin/bash
#
# The Qubes OS Project, http://www.qubes-os.org
#
# Copyright (C) 2011  Tomasz Sterna <tomek@xiaoka.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
#

# Switch user to 'user'
[[ "$USER" != "user" ]] && exec su user -c $0

# Save user environment for later
umask 0077
rm -f /tmp/qubes-session-env
env > /tmp/qubes-session-env

# Wake waiting for environment processes
[ -s /tmp/qubes-session-waiter ] && kill -KILL `cat /tmp/qubes-session-waiter` 

# Get VM type from XenStore
VMTYPE=`/usr/bin/xenstore-read qubes_vm_type`

if [[ -n "$VMTYPE" ]] && [[ "$VMTYPE" != "DisposableVM" ]]; then
# Process XDG Autostart files
shopt -s nullglob
for D in /etc/xdg/autostart/*.desktop; do
	UPDTYPE=`/usr/bin/xenstore-read qubes_vm_updateable`
	[[ $UPDTYPE == 'True' ]] && UPDTYPE="UpdateableVM" || UPDTYPE="NonUpdateableVM"
	MATCH="\(QUBES\|$VMTYPE\|$UPDTYPE\)"
	[[ -n "$XDG_CONFIG_DIRS" ]] && [[ -d "$XDG_CONFIG_DIRS/autostart" ]] && USER_AUTOSTART="$XDG_CONFIG_DIRS/autostart" || USER_AUTOSTART="$HOME/.config/autostart"
	[[ -r "$USER_AUTOSTART/${D##*/}" ]] && D="$D $USER_AUTOSTART/${D##*/}"
	# Skip Terminal, Hidden, NotShowIn=QUBES and ! OnlyShowIn=QUBES
	[[ -n `sed -n "/^Terminal.*[tT1]/p;/^Hidden.*[tT1]/p;/^X-GNOME-Autostart-enabled.*[fF0]/p;/^NotShowIn.*=.*$MATCH/p;/^OnlyShowIn/{s/.*$MATCH.*//;p}" $D` ]] && continue
	# Extract Exec= line
	EXEC=`sed -n '/^Exec[ \t=]/s/^[^=]\+=[ \t]*//p' $D | tail -n1`
	[[ -z "$EXEC" ]] && continue
	$EXEC &
done
fi # VMTYPE

# Wait some time to pick up zombie children
sleep 1m

# Now hang myself so Xorg may live :'(
# ____
# |/ |
# |  O
# | /|\
# | / \
# |
kill -STOP $$
