#!/usr/bin/python
import subprocess
import os

vm_layout = "%s/.config/qubes-keyboard-layout.rc" % os.getenv("HOME")
if os.path.exists(vm_layout):
	file = open(vm_layout)
	current_layout = file.readline().strip()
	file.close()
	subprocess.call(['setxkbmap', current_layout])
